// Generated by tools/build_details_icons.py; do not edit.

/** Where the rebuilt Details class icon sheets hold each icon: left, right, top, bottom. */
export const DETAILS_ICON_COORDS: { [key: string]: [number, number, number, number] } = {
    ['Alliance']: [0.375, 0.5, 0.25, 0.375],
    ['BATTLEMAGE']: [0.25, 0.375, 0.125, 0.25],
    ['DEATHKNIGHT']: [0.125, 0.25, 0.125, 0.25],
    ['DRUID']: [0.375, 0.5, 0, 0.125],
    ['ENEMY']: [0.75, 0.875, 0.125, 0.25],
    ['HUNTER']: [0.5, 0.625, 0, 0.125],
    ['Horde']: [0.5, 0.625, 0.25, 0.375],
    ['MAGE']: [0.125, 0.25, 0, 0.125],
    ['MARAUDER']: [0.375, 0.5, 0.125, 0.25],
    ['MONK']: [0.5, 0.625, 0.125, 0.25],
    ['MONSTER']: [0.875, 1, 0.125, 0.25],
    ['MOUNTAINKING']: [0.625, 0.75, 0.125, 0.25],
    ['PALADIN']: [0, 0.125, 0.125, 0.25],
    ['PET']: [0, 0.125, 0.25, 0.375],
    ['PRIEST']: [0.75, 0.875, 0, 0.125],
    ['ROGUE']: [0.25, 0.375, 0, 0.125],
    ['SHAMAN']: [0.625, 0.75, 0, 0.125],
    ['UNGROUPPLAYER']: [0.25, 0.375, 0.25, 0.375],
    ['UNKNOW']: [0.125, 0.25, 0.25, 0.375],
    ['WARLOCK']: [0.875, 1, 0, 0.125],
    ['WARRIOR']: [0, 0.125, 0, 0.125],
};
