// Generated by tools/build_chi_assets.py from the retail Monk HUD art; do not edit.

/** A piece of the Chi atlas: its display size and texture coordinates (inset half a texel). */
export interface ChiPiece {
    width: number;
    height: number;
    left: number;
    right: number;
    top: number;
    bottom: number;
}

export const CHI_TEXTURE = 'Interface\\MonkChi\\Chi.tga';
/** The size of the texture in pixels, for |T texture markup in text. */
export const CHI_TEXTURE_SIZE = { width: 256, height: 128 };

export const CHI_ART = {
    slot: { width: 26, height: 26, left: 0.033203, right: 0.232422, top: 0.066406, bottom: 0.464844 },
    slotActive: { width: 26, height: 26, left: 0.267578, right: 0.466797, top: 0.066406, bottom: 0.464844 },
    flash: { width: 26, height: 26, left: 0.501953, right: 0.701172, top: 0.066406, bottom: 0.464844 },
    orb: { width: 15, height: 15, left: 0.736328, right: 0.849609, top: 0.066406, bottom: 0.292969 },
};
