// Generated by datascripts/ChiAddonData.ts from the Chi spells; do not edit.

/** Chi cost of every Chi spender, by spell id. */
export const CHI_COSTS: { [spellId: number]: number } = {
    [81814]: 1,
    [82245]: 1,
    [81815]: 2,
    [81854]: 2,
    [81846]: 2,
    [82244]: 2,
    [81857]: 3,
    [81841]: 3,
    [81848]: 3,
    [81849]: 3,
    [81850]: 3,
    [81851]: 3,
};

/** Spenders the Combo Breaker buff makes free. */
export const FREE_WITH_COMBO_BREAKER: number[] = [81815];
export const COMBO_BREAKER = 81858;
