import * as fs from "fs";
import * as path from "path";
import { finish } from "wow/data";
import { CHI_TAGS, ChiCost, taggedSpells } from "./abilities/Chi";

/**
 * The action bars cannot tell that a Chi spender lacks Chi: the spell costs
 * no power. Once every Chi spell has been created and tagged, this writes
 * their ids and costs into the addon, which `build addon` then compiles.
 */
const GENERATED_FILE = path.resolve(__dirname, '../../addon/ChiSpells.ts');
const COSTS: ChiCost[] = [1, 2, 3];

finish('monk-chi-addon-data', () => {
    const costs: string[] = [];
    COSTS.forEach(chi => taggedSpells(CHI_TAGS.cost(chi)).forEach(spellId => costs.push(`    [${spellId}]: ${chi},`)));
    const [comboBreaker] = taggedSpells(CHI_TAGS.comboBreaker);
    const source = [
        '// Generated by datascripts/ChiAddonData.ts from the Chi spells; do not edit.',
        '',
        '/** Chi cost of every Chi spender, by spell id. */',
        'export const CHI_COSTS: { [spellId: number]: number } = {',
        ...costs,
        '};',
        '',
        '/** Spenders the Combo Breaker buff makes free. */',
        `export const FREE_WITH_COMBO_BREAKER: number[] = [${taggedSpells(CHI_TAGS.blackoutKick).join(', ')}];`,
        `export const COMBO_BREAKER = ${comboBreaker};`,
        '',
    ].join('\n');
    // Unchanged output is left alone so the addon is not rebuilt for nothing.
    if (!fs.existsSync(GENERATED_FILE) || fs.readFileSync(GENERATED_FILE, 'utf8') !== source) {
        fs.writeFileSync(GENERATED_FILE, source);
    }
});
