import {
    ARCANE_SHOCKWAVE, FROSTBLADE, ICE_FORTRESS, PROVOKE, RIME_GUARD,
} from "../abilities/BattleMageAbilities";
import {
    abilityFlat, abilityPercent, ALL_SCHOOLS, armorFromItems, attackerMeleeCrit, block, createTalentTree,
    damageDone, damageTaken, dodge, MAGIC_SCHOOLS, parry, statPercent, threat,
} from "./TalentBuilder";

const THREAT_ABILITIES = [ARCANE_SHOCKWAVE, FROSTBLADE];

export const FROSTGUARD_TREE = createTalentTree({
    id: 'frostguard',
    name: 'Frostguard',
    tabIndex: 1,
    background: 'MageFrost',
    icon: 'Spell_Frost_FrostArmor02',
    talents: [
        {
            kind: 'passive', id: 'glacial-plating', row: 0, column: 1, ranks: 5,
            name: 'Glacial Plating', icon: 'Spell_Frost_FrostArmor',
            description: 'Increases your armor value from items by $s1%.',
            effects: [armorFromItems(2)],
        },
        {
            kind: 'passive', id: 'frozen-resolve', row: 0, column: 2, ranks: 5,
            name: 'Frozen Resolve', icon: 'Spell_Frost_WindWalkOn',
            description: 'Increases your chance to dodge by $s1%.',
            effects: [dodge(1)],
        },
        {
            kind: 'passive', id: 'rime-bulwark', row: 1, column: 0, ranks: 5,
            name: 'Rime Bulwark', icon: 'Spell_Holy_DevotionAura',
            description: 'Increases your Stamina by $s1%.',
            effects: [statPercent('STAMINA', 2)],
        },
        {
            kind: 'passive', id: 'improved-provoke', row: 1, column: 1, ranks: 2,
            name: 'Improved Provoke', icon: 'Spell_Nature_Reincarnation',
            description: 'Reduces the cooldown of Provoke by $/1000;S1 sec.',
            effects: [abilityFlat('COOLDOWN', -1000, [PROVOKE])],
        },
        {
            kind: 'passive', id: 'improved-frostblade', row: 1, column: 2, ranks: 3,
            name: 'Improved Frostblade', icon: 'Spell_Frost_FrostBrand',
            description: 'Increases the damage of Frostblade by $s1%.',
            effects: [abilityPercent('DAMAGE', 5, [FROSTBLADE])],
        },
        {
            kind: 'passive', id: 'deflecting-frost', row: 2, column: 0, ranks: 5,
            name: 'Deflecting Frost', icon: 'Ability_Parry',
            description: 'Increases your chance to parry by $s1%.',
            effects: [parry(1)],
        },
        {
            kind: 'passive', id: 'glacial-resolve', row: 2, column: 1, ranks: 3,
            name: 'Glacial Resolve', icon: 'Spell_Frost_ChillingArmor',
            description: 'Increases all threat you generate by $s1%.',
            effects: [threat(15)],
        },
        {
            kind: 'passive', id: 'frozen-shield', row: 3, column: 0, ranks: 3,
            name: 'Frozen Shield', icon: 'Ability_Defend',
            description: 'Increases your chance to block by $s1%.',
            effects: [block(2)],
        },
        {
            kind: 'passive', id: 'permafrost', row: 3, column: 2, ranks: 3,
            name: 'Permafrost', icon: 'Spell_Frost_Wisp',
            description: 'Reduces all damage taken by $S1%.',
            effects: [damageTaken(ALL_SCHOOLS, -1)],
        },
        {
            kind: 'passive', id: 'improved-rime-guard', row: 4, column: 0, ranks: 2,
            name: 'Improved Rime Guard', icon: 'Spell_Frost_FrostArmor02',
            description: 'Reduces the cooldown of Rime Guard by $/1000;S1 sec.',
            effects: [abilityFlat('COOLDOWN', -10000, [RIME_GUARD])],
        },
        {
            kind: 'passive', id: 'hardened-frost', row: 4, column: 1, ranks: 5,
            name: 'Hardened Frost', icon: 'Spell_Frost_FrozenCore',
            description: 'Reduces the chance you\'ll be critically hit by melee attacks by $S1%.',
            effects: [attackerMeleeCrit(-1)],
        },
        {
            kind: 'passive', id: 'shockwave-mastery', row: 5, column: 1, ranks: 2,
            name: 'Shockwave Mastery', icon: 'Spell_Arcane_ArcaneTorrent',
            description: 'Increases the threat generated by Arcane Shockwave and Frostblade by $s1%.',
            effects: [abilityPercent('THREAT', 25, THREAT_ABILITIES)],
        },
        {
            kind: 'passive', id: 'chilled-to-the-bone', row: 5, column: 2, ranks: 3,
            name: 'Chilled to the Bone', icon: 'Spell_Frost_FrostBolt02',
            description: 'Increases all Frost damage you deal by $s1%.',
            effects: [damageDone(['FROST'], 2)],
        },
        { kind: 'active', id: 'ice-fortress', row: 6, column: 1, ability: ICE_FORTRESS },
        {
            kind: 'passive', id: 'glacial-mastery', row: 7, column: 1, ranks: 3,
            requires: 'ice-fortress',
            name: 'Glacial Mastery', icon: 'Spell_Frost_Glacier',
            description: 'Reduces the cooldown of Ice Fortress by $/1000;S1 sec.',
            effects: [abilityFlat('COOLDOWN', -30000, [ICE_FORTRESS])],
        },
        {
            kind: 'passive', id: 'spell-deflection', row: 7, column: 2, ranks: 5,
            name: 'Spell Deflection', icon: 'Spell_Frost_FrostWard',
            description: 'Reduces all spell damage taken by $S1%.',
            effects: [damageTaken(MAGIC_SCHOOLS, -1)],
        },
        {
            kind: 'passive', id: 'avalanche', row: 8, column: 0, ranks: 2,
            name: 'Avalanche', icon: 'Spell_Frost_IceShock',
            description: 'Increases the critical strike chance of Arcane Shockwave and Frostblade by $s1%.',
            effects: [abilityFlat('CRITICAL_CHANCE', 5, THREAT_ABILITIES)],
        },
        {
            kind: 'passive', id: 'frigid-vigor', row: 8, column: 2, ranks: 3,
            name: 'Frigid Vigor', icon: 'Spell_Frost_ArcticWinds',
            description: 'Increases your Strength by $s1%.',
            effects: [statPercent('STRENGTH', 2)],
        },
        {
            kind: 'passive', id: 'frozen-core', row: 9, column: 1, ranks: 3,
            name: 'Frozen Core', icon: 'Spell_Frost_FrostShock',
            description: 'Increases your armor value from items by an additional $s1%.',
            effects: [armorFromItems(3)],
        },
        {
            kind: 'passive', id: 'avatar-of-winter', row: 10, column: 1, ranks: 1,
            name: 'Avatar of Winter', icon: 'Spell_Frost_SummonWaterElemental_2',
            description: 'Reduces all damage taken by $S1% and increases your Stamina by $s2%.',
            effects: [
                damageTaken(ALL_SCHOOLS, -3),
                statPercent('STAMINA', 5),
            ],
        },
    ],
});
