import * as fs from "fs";
import * as path from "path";
import { finish } from "wow/data";
import { std } from "wow/wotlk";

/**
 * The 3.3.5 talent API cannot tell an ability talent (drawn as a square, as
 * in retail) from a passive one (a circle), but the talent's spell can. Once
 * every module has created its talents, this writes the ids of all ability
 * talents into the addon, which `build addon` then compiles.
 */
const GENERATED_FILE = path.resolve(__dirname, '../../addon/model/AbilityTalents.ts');

const SPELL_ATTR0_PASSIVE = 0x40;
const SPELL_EFFECT_LEARN_SPELL = 36;

function isAbility(spellId: number) {
    const spell = std.DBC.Spell.query({ ID: spellId });
    if (spell === undefined) {
        return false;
    }
    // Some passive talents exist only to teach an ability.
    const teachesSpell = spell.Effect.get().includes(SPELL_EFFECT_LEARN_SPELL);
    return (spell.Attributes.get() & SPELL_ATTR0_PASSIVE) === 0 || teachesSpell;
}

finish('talentui-ability-talents', () => {
    const ids = std.DBC.Talent.queryAll({})
        .filter(talent => isAbility(talent.SpellRank.getIndex(0)))
        .map(talent => talent.ID.get())
        .sort((a, b) => a - b);
    const source = [
        '// Generated by datascripts/datascripts.ts from the talent and spell DBCs; do not edit.',
        '',
        '/** Talents (by Talent.dbc id) whose first rank is an ability rather than a passive. */',
        `export const ABILITY_TALENTS: number[] = [${ids.join(', ')}];`,
        '',
    ].join('\n');
    // Unchanged output is left alone so the addon is not rebuilt for nothing.
    if (!fs.existsSync(GENERATED_FILE) || fs.readFileSync(GENERATED_FILE, 'utf8') !== source) {
        fs.writeFileSync(GENERATED_FILE, source);
    }
});
