"""
Builds the Chi bar textures from the retail Monk HUD art.

    py modules/monk/tools/build_chi_assets.py [retail Interface folder]

Crops the gold Chi slot rings, the lit jade orb and the flash ring from
retail's HUD/UIMonkChi2x.BLP into one lossless TGA atlas and generates
addon/ChiArt.ts with their coordinates, so the addon and the texture
cannot drift apart.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw

MODULE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(MODULE.parents[1] / 'tools'))
from retail_art import DEFAULT_RETAIL_INTERFACE, decode_blp, write_tga, ts_string  # noqa: E402

SOURCE = 'HUD/UIMonkChi2x.BLP'
TEXTURE = MODULE / 'assets' / 'Interface' / 'MonkChi' / 'Chi.tga'
CLIENT_TEXTURE = 'Interface\\MonkChi\\Chi.tga'
GENERATED_TS = MODULE / 'addon' / 'ChiArt.ts'

ATLAS_SIZE = (256, 128)
GUTTER = 8
# The retail art is 2x; pieces are shown at half size.
DISPLAY_SCALE = 0.5

# Crops (x, y, w, h) of the 2x art. The rings are centered on their dark
# hole, which the orb fills; the flash ring is centered too. The art packs
# sprites tightly, so round pieces are cut to their circle to drop the
# neighbors' edges.
ROUND_PIECES = {'slot', 'slotActive', 'flash'}
PIECES = {
    'slot': (446, 77, 52, 52),
    'slotActive': (446, 129, 52, 52),
    'flash': (0, 291, 52, 52),
    'orb': (30, 370, 30, 30),
}


def layout():
    """Places the pieces left to right in one row with gutters; returns name -> (x, y, w, h)."""
    placed = {}
    x = GUTTER
    for name, (_, _, w, h) in PIECES.items():
        if x + w + GUTTER > ATLAS_SIZE[0] or GUTTER + h + GUTTER > ATLAS_SIZE[1]:
            raise ValueError(f'atlas pieces do not fit; {name} overflows')
        placed[name] = (x, GUTTER, w, h)
        x += w + GUTTER
    return placed


def cut_to_circle(piece: Image.Image) -> Image.Image:
    mask = Image.new('L', piece.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0, piece.width - 1, piece.height - 1), fill=255)
    alpha = Image.composite(piece.getchannel('A'), mask, mask)
    piece.putalpha(alpha)
    return piece


def write_atlas(interface: Path, placed):
    source = decode_blp(interface / SOURCE)
    atlas = Image.new('RGBA', ATLAS_SIZE, (0, 0, 0, 0))
    for name, (x, y, w, h) in PIECES.items():
        piece = source.crop((x, y, x + w, y + h))
        if name in ROUND_PIECES:
            piece = cut_to_circle(piece)
        atlas.alpha_composite(piece, placed[name][:2])
    write_tga(atlas, TEXTURE)


def write_typescript(placed):
    width, height = ATLAS_SIZE
    lines = [
        '// Generated by tools/build_chi_assets.py from the retail Monk HUD art; do not edit.',
        '',
        '/** A piece of the Chi atlas: its display size and texture coordinates (inset half a texel). */',
        'export interface ChiPiece {',
        '    width: number;',
        '    height: number;',
        '    left: number;',
        '    right: number;',
        '    top: number;',
        '    bottom: number;',
        '}',
        '',
        f'export const CHI_TEXTURE = {ts_string(CLIENT_TEXTURE)};',
        '/** The size of the texture in pixels, for |T texture markup in text. */',
        f'export const CHI_TEXTURE_SIZE = {{ width: {width}, height: {height} }};',
        '',
        'export const CHI_ART = {',
    ]
    for name, (x, y, w, h) in placed.items():
        lines.append(
            f'    {name}: {{ width: {w * DISPLAY_SCALE:g}, height: {h * DISPLAY_SCALE:g},'
            f' left: {(x + 0.5) / width:.6f}, right: {(x + w - 0.5) / width:.6f},'
            f' top: {(y + 0.5) / height:.6f}, bottom: {(y + h - 0.5) / height:.6f} }},')
    lines += ['};', '']
    GENERATED_TS.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_TS.write_text('\n'.join(lines), encoding='utf-8', newline='\n')


def main():
    interface = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_RETAIL_INTERFACE
    placed = layout()
    write_atlas(interface, placed)
    write_typescript(placed)
    for name, (x, y, w, h) in placed.items():
        print(f'{name}: {w}x{h} at {x},{y}')


if __name__ == '__main__':
    main()
