TYPE=VIEW
query=select (case when (`default.dataset.world.dest`.`disables`.`sourceType` = 0) then \'DISABLE_TYPE_SPELL\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 1) then \'DISABLE_TYPE_QUEST\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 2) then \'DISABLE_TYPE_MAP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 3) then \'DISABLE_TYPE_BATTLEGROUND\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 4) then \'DISABLE_TYPE_ACHIEVEMENT_CRITERIA\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 5) then \'DISABLE_TYPE_OUTDOORPVP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 6) then \'DISABLE_TYPE_VMAP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 7) then \'DISABLE_TYPE_MMAP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 8) then \'DISABLE_TYPE_LFG_MAP\' else `default.dataset.world.dest`.`disables`.`sourceType` end) AS `sourceType`,`default.dataset.world.dest`.`disables`.`entry` AS `entry`,`default.dataset.world.dest`.`disables`.`flags` AS `flags`,`default.dataset.world.dest`.`disables`.`params_0` AS `params_0`,`default.dataset.world.dest`.`disables`.`params_1` AS `params_1`,`default.dataset.world.dest`.`disables`.`comment` AS `comment` from `default.dataset.world.dest`.`disables`
md5=020036943b26314956a0ed1f8ea66417
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2026-10-05 19:41:03
create-version=1
source=select (case when (`disables`.`sourceType` = 0) then \'DISABLE_TYPE_SPELL\' when (`disables`.`sourceType` = 1) then \'DISABLE_TYPE_QUEST\' when (`disables`.`sourceType` = 2) then \'DISABLE_TYPE_MAP\' when (`disables`.`sourceType` = 3) then \'DISABLE_TYPE_BATTLEGROUND\' when (`disables`.`sourceType` = 4) then \'DISABLE_TYPE_ACHIEVEMENT_CRITERIA\' when (`disables`.`sourceType` = 5) then \'DISABLE_TYPE_OUTDOORPVP\' when (`disables`.`sourceType` = 6) then \'DISABLE_TYPE_VMAP\' when (`disables`.`sourceType` = 7) then \'DISABLE_TYPE_MMAP\' when (`disables`.`sourceType` = 8) then \'DISABLE_TYPE_LFG_MAP\' else `disables`.`sourceType` end) AS `sourceType`,`disables`.`entry` AS `entry`,`disables`.`flags` AS `flags`,`disables`.`params_0` AS `params_0`,`disables`.`params_1` AS `params_1`,`disables`.`comment` AS `comment` from `disables`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select (case when (`default.dataset.world.dest`.`disables`.`sourceType` = 0) then \'DISABLE_TYPE_SPELL\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 1) then \'DISABLE_TYPE_QUEST\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 2) then \'DISABLE_TYPE_MAP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 3) then \'DISABLE_TYPE_BATTLEGROUND\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 4) then \'DISABLE_TYPE_ACHIEVEMENT_CRITERIA\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 5) then \'DISABLE_TYPE_OUTDOORPVP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 6) then \'DISABLE_TYPE_VMAP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 7) then \'DISABLE_TYPE_MMAP\' when (`default.dataset.world.dest`.`disables`.`sourceType` = 8) then \'DISABLE_TYPE_LFG_MAP\' else `default.dataset.world.dest`.`disables`.`sourceType` end) AS `sourceType`,`default.dataset.world.dest`.`disables`.`entry` AS `entry`,`default.dataset.world.dest`.`disables`.`flags` AS `flags`,`default.dataset.world.dest`.`disables`.`params_0` AS `params_0`,`default.dataset.world.dest`.`disables`.`params_1` AS `params_1`,`default.dataset.world.dest`.`disables`.`comment` AS `comment` from `default.dataset.world.dest`.`disables`
