import * as fs from "fs";
import * as path from "path";
import { finish } from "wow/data";
import { growingWeapons } from "./GrowingWeapon";

/**
 * Livescripts cannot read datascript values, and tags cannot carry one array
 * per weapon, so once every module has made its weapons this writes them into
 * the livescripts, which `build scripts` then compiles.
 */
const GENERATED_FILE = path.resolve(__dirname, '../../livescripts/GrowingWeaponData.ts');

finish('growingweapons-livescript-data', () => {
    const weapons = growingWeapons().map(weapon => [
        '    {',
        `        item: ${weapon.item},`,
        `        bonuses: [${weapon.bonuses.map(bonus => `'${bonus}'`).join(', ')}],`,
        '        levels: [',
        ...weapon.levels.map(level =>
            `            { enchantment: ${level.enchantment}, amounts: [${level.amounts.join(', ')}] },`),
        '        ],',
        '    },',
    ].join('\n'));
    const source = [
        '// Generated by datascripts/LivescriptData.ts from every growing weapon; do not edit.',
        'import { GrowingWeapon } from "./GrowingWeapon";',
        '',
        `export const GROWING_WEAPONS: GrowingWeapon[] = [${weapons.length > 0 ? '\n' + weapons.join('\n') + '\n' : ''}];`,
        '',
    ].join('\n');
    // Unchanged output is left alone so the livescripts are not rebuilt for nothing.
    if (!fs.existsSync(GENERATED_FILE) || fs.readFileSync(GENERATED_FILE, 'utf8') !== source) {
        fs.writeFileSync(GENERATED_FILE, source);
    }
});
