// Generated by tools/build_assets.py from the retail interface art; do not edit.

/** A piece of the parts atlas: its display size and texture coordinates (inset half a texel). */
export interface AtlasPiece {
    width: number;
    height: number;
    left: number;
    right: number;
    top: number;
    bottom: number;
}

export const PARTS_TEXTURE = 'Interface\\GrowingWeapons\\Parts.tga';
export const BACKDROP_TEXTURE = 'Interface\\GrowingWeapons\\Backdrop';

export const ATLAS = {
    badge: { width: 44, height: 44, left: 0.454102, right: 0.624023, top: 0.016602, bottom: 0.186523 },
    bamboo: { width: 244, height: 14, left: 0.016602, right: 0.967773, top: 0.325195, bottom: 0.377930 },
    barFill: { width: 168, height: 10, left: 0.016602, right: 0.670898, top: 0.395508, bottom: 0.432617 },
    barFrame: { width: 172, height: 14.5, left: 0.016602, right: 0.686523, top: 0.252930, bottom: 0.307617 },
    barTrack: { width: 168, height: 10, left: 0.016602, right: 0.670898, top: 0.450195, bottom: 0.487305 },
    glow: { width: 108, height: 56.5, left: 0.016602, right: 0.436523, top: 0.016602, bottom: 0.235352 },
    goldLine: { width: 198.5, height: 2, left: 0.016602, right: 0.790039, top: 0.504883, bottom: 0.510742 },
};
